pipeline {
     agent { label 'slave-node'}
    options {
        ansiColor('xterm')
    }
    stages {
     stage ('DEPLOY') {
            steps {
                 sh 'cat bancoripley/k8s/deployment.yaml | sed "s/{{TAG}}/$TAG/g" | kubectl apply -f -'
            }
        }}}